import { describe, expect, it } from "bun:test";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { OpenPullRequestSummary } from "../src/adapters/github.ts";
import {
  buildBranchName,
  findExistingPrForTicket,
  resolveTestGateCommand,
  sanitizePrBody,
} from "../src/handlers/code.ts";

describe("buildBranchName", () => {
  it("prefixes the classified type and lowercases the identifier", () => {
    expect(buildBranchName("ERT-1891", "Roll for first sets winnerId", "fix")).toBe(
      "fix/ert-1891-roll-for-first-sets-winnerid",
    );
  });

  it("falls back to the legacy format without a type", () => {
    expect(buildBranchName("ERT-1891", "Roll for first")).toBe(
      "ERT-1891-roll-for-first",
    );
  });

  it("ignores unknown types (junk in the DB must not shape branch names)", () => {
    expect(buildBranchName("ERT-1", "thing", "bugfix")).toBe("ERT-1-thing");
  });
});

describe("sanitizePrBody", () => {
  const signature =
    "🤖 Generated by [gary-707-labs](https://github.com/apps/gary-707-labs)";

  it("drops trailing garbage after the signature line", () => {
    const body = `## Summary\nstuff\n\n${signature}\nEOF\n)`;
    expect(sanitizePrBody(body)).toBe(`## Summary\nstuff\n\n${signature}`);
  });

  it("leaves a clean body untouched", () => {
    const body = `## Summary\nstuff\n\n${signature}`;
    expect(sanitizePrBody(body)).toBe(body);
  });

  it("unwraps a full-body markdown fence", () => {
    const inner = `## Summary\nstuff\n\n${signature}`;
    expect(sanitizePrBody("```markdown\n" + inner + "\n```")).toBe(inner);
  });

  it("passes through a body without a signature", () => {
    expect(sanitizePrBody("## Summary\nno signature here\n")).toBe(
      "## Summary\nno signature here",
    );
  });
});

describe("findExistingPrForTicket", () => {
  const pr = (
    number: number,
    headRef: string,
    title: string,
  ): OpenPullRequestSummary => ({
    number,
    url: `https://github.com/o/r/pull/${number}`,
    title,
    headRef,
    authorLogin: "someone",
  });

  it("matches the identifier in the head ref, case-insensitively", () => {
    const hit = findExistingPrForTicket(
      [pr(512, "ert-1891-roll-for-first", "fix roll for first")],
      "ERT-1891",
    );
    expect(hit?.number).toBe(512);
  });

  it("matches the identifier in the title", () => {
    const hit = findExistingPrForTicket(
      [pr(512, "some-branch", "fix: roll for first (ERT-1891)")],
      "ERT-1891",
    );
    expect(hit?.number).toBe(512);
  });

  it("does not let ERT-1 match ERT-1891", () => {
    expect(
      findExistingPrForTicket(
        [pr(512, "ert-1891-roll-for-first", "fix (ERT-1891)")],
        "ERT-1",
      ),
    ).toBeNull();
  });

  it("returns null when nothing references the ticket", () => {
    expect(
      findExistingPrForTicket([pr(1, "chore/deps", "bump deps")], "ERT-42"),
    ).toBeNull();
  });
});

describe("resolveTestGateCommand", () => {
  const withPackageJson = (scripts: Record<string, string> | null): string => {
    const dir = mkdtempSync(join(tmpdir(), "gary-testgate-"));
    if (scripts !== null) {
      writeFileSync(join(dir, "package.json"), JSON.stringify({ scripts }));
    }
    return dir;
  };

  it("prefers test:run when present", () => {
    const dir = withPackageJson({ test: "vitest", "test:run": "vitest run" });
    try {
      expect(resolveTestGateCommand(dir)).toBe("bun run test:run");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("accepts a non-watch test script", () => {
    const dir = withPackageJson({ test: "vitest run" });
    try {
      expect(resolveTestGateCommand(dir)).toBe("bun run test");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("rejects a watch-mode test script (bare vitest would hang the gate)", () => {
    const dir = withPackageJson({ test: "vitest" });
    try {
      expect(resolveTestGateCommand(dir)).toBeNull();
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("returns null when there is no package.json", () => {
    const dir = withPackageJson(null);
    try {
      expect(resolveTestGateCommand(dir)).toBeNull();
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("honors GARY_TEST_COMMAND verbatim", () => {
    const dir = withPackageJson({ test: "vitest" });
    process.env.GARY_TEST_COMMAND = "bun run test:unit";
    try {
      expect(resolveTestGateCommand(dir)).toBe("bun run test:unit");
    } finally {
      delete process.env.GARY_TEST_COMMAND;
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("disables the gate on GARY_TEST_COMMAND=off", () => {
    const dir = withPackageJson({ "test:run": "vitest run" });
    process.env.GARY_TEST_COMMAND = "off";
    try {
      expect(resolveTestGateCommand(dir)).toBeNull();
    } finally {
      delete process.env.GARY_TEST_COMMAND;
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
