import { resolve } from "node:path";
import type { CloudflareClient } from "../adapters/cloudflare.ts";
import type { GitHubClient } from "../adapters/github.ts";
import type { GLMClient } from "../adapters/glm.ts";
import type { AssignedIssue, IssueComment, LinearAdapter } from "../adapters/linear.ts";
import { runAgentLoop } from "../agent/loop.ts";
import { composeSystemPrompt } from "../agent/prompts.ts";
import {
  createWorktree,
  ensureBareClone,
  getCommitLog,
  getDiff,
  hasCommitsAhead,
  pushBranch,
  slugify,
} from "../git.ts";
import { LocalExecutor } from "../executors/local.ts";
import { log } from "../logger.ts";
import {
  formatProjectContext,
  loadProjectContext,
  loadSkillIndex,
} from "../skills.ts";
import type { DB } from "../state/db.ts";
import { recordPr, setTerminalState } from "../state/queries.ts";

const BASE_BRANCH = "main";

const CODE_TASK_INSTRUCTIONS = `You are working on a Linear ticket for 707 Labs. Make the smallest change that solves the ticket and stop.

You can use tools to read, edit, run bash commands, and commit. When you're done, call finish() with a one-sentence summary.

Rules:
- Read before you write. Look at the existing code, the project's conventions (CLAUDE.md, AGENTS.md, .claude/skills/), and any related files before changing anything.
- Make the smallest change that solves the ticket. Don't refactor unrelated code.
- BEFORE calling finish, run \`bun run check\` (the project's typecheck/svelte-check command). If there are errors caused by your changes, fix them and re-run. The repo has a pre-push hook that runs the same command — your push will be rejected if it fails.
- Run other tests if there's an obvious command for the area you touched (look at package.json scripts and tests in the changed file's directory). If tests fail, try to fix them.
- If the ticket is ambiguous, make a reasonable choice and note it in finish()'s summary.
- If you realize the ticket is bigger than you can handle, call finish() with a summary explaining what you got done and what's left. Escalation will happen automatically.
- Don't install new dependencies unless the ticket clearly requires it.
- Commit your changes before calling finish.`;

export const PR_BODY_TASK_INSTRUCTIONS = `Write a PR title and body for the changes you just made. Use voice.md examples 5 (small, confident) and 6 (medium, with uncertainty) as your structural template — match that exact format. Pick the level of detail based on the size and certainty of this change.

Output ONLY the PR body markdown. Do not output the title — the title is generated separately. Do not output any preamble like "Here is the PR body".

Required sections, in order:
1. \`## Summary\` — 1-3 short paragraphs and/or bullets explaining what changed and why. Lead with the most important change.
2. \`## Things i'm less sure about\` — only if there's genuine uncertainty. Skip the section entirely if the change is small and confident.
3. \`## Test plan\` — markdown checklist. Each line is \`- [x] <command>\` for things you ran, \`- [ ] <thing>\` for things still to verify (always include \`- [ ] CI green\`). At minimum include the typecheck command you ran (\`bun run check\` or equivalent).
4. \`## Follow-ups\` — only if there are genuine related tasks not in scope here.
5. A blank line, then \`closes [<TICKET-ID>]\` (uppercase).
6. A blank line, then a parenthetical "(i'm gary — ai agent. <specific things to double-check>.)" line.
7. A blank line, then the signature: \`🤖 Generated by [gary-707-labs](https://github.com/apps/gary-707-labs)\`

Voice rules: lowercase-friendly, contractions, terse. Don't fake confidence — if you're uncertain, say so in the "less sure about" section. If the test plan only has one or two items, that's fine — don't pad.`;

export const PR_TITLE_TASK_INSTRUCTIONS = `Write a PR title in conventional commit format with a Linear ticket suffix.

Format: \`<type>(<scope>): <description> (<TICKET-ID>)\`

- type: one of feat, fix, refactor, chore, docs, test, perf
- scope: optional but encouraged — derive from the area of code changed (e.g., screenshot, scryfall, hotkey, decks)
- description: lowercase, no leading capital, no trailing period, present tense ("add x" not "added x" or "adds x")
- ticket: include the ticket ID in parentheses at the end, uppercase, no \`closes\` keyword

Output ONLY the title on a single line. No quotes, no preamble.

Examples:
\`feat(hotkey): extend F to toggle face-down on morph cards (ERT-1615)\`
\`fix(scryfall): split rate limiter into interactive and batch queues (ERT-1610)\`
\`refactor(delta): audit PlayerStateDelta against PlayerGameState (ERT-1613)\``;

export interface CodeHandlerDeps {
  db: DB;
  linear: LinearAdapter;
  github: GitHubClient;
  glm: GLMClient;
  cloudflare: CloudflareClient | null;
  reposDir: string;
  workspacesDir: string;
  agentLoopMaxIterations: number;
  agentLoopTimeoutMs: number;
}

export interface CodeHandlerArgs {
  issue: AssignedIssue;
  comments: readonly IssueComment[];
  repo: string; // "owner/repo"
}

export interface CodeHandlerResult {
  status: "pr_opened" | "no_changes" | "agent_failed";
  prUrl?: string;
  prNumber?: number;
  branch: string;
  summary: string | null;
}

export async function runCodeHandler(
  deps: CodeHandlerDeps,
  args: CodeHandlerArgs,
): Promise<CodeHandlerResult> {
  const [owner, name] = args.repo.split("/") as [string, string];

  const branch = `${args.issue.identifier}-${slugify(args.issue.title)}`;
  const worktreePath = resolve(deps.workspacesDir, args.issue.identifier);

  log.info("code handler starting", {
    issue: args.issue.identifier,
    repo: args.repo,
    branch,
    worktreePath,
  });

  const freshUrl = await deps.github.cloneUrl(owner, name);
  const bareDir = await ensureBareClone({
    owner,
    repo: name,
    reposDir: deps.reposDir,
    freshTokenUrl: freshUrl,
  });

  const viewer = await deps.github.getViewer();
  const authorEmail = `${viewer.login}@users.noreply.github.com`;

  await createWorktree({
    bareDir,
    worktreePath,
    branch,
    baseBranch: BASE_BRANCH,
    authorName: viewer.login,
    authorEmail,
  });

  const executor = new LocalExecutor(worktreePath);
  const system = composeSystemPrompt({ taskInstructions: CODE_TASK_INSTRUCTIONS });
  const projectSection = formatProjectContext(
    loadProjectContext(worktreePath),
    loadSkillIndex(worktreePath),
  );
  const ticketMessage = renderTicketForAgent(args.issue, args.comments, {
    worktreePath,
    branch,
  });
  const taskMessage = projectSection
    ? `${projectSection}\n\n---\n\n${ticketMessage}`
    : ticketMessage;

  const loopResult = await runAgentLoop({
    glm: deps.glm,
    executor,
    systemPrompt: system,
    task: taskMessage,
    maxIterations: deps.agentLoopMaxIterations,
    timeoutMs: deps.agentLoopTimeoutMs,
    temperature: 0.3,
    linear: deps.linear,
    github: deps.github,
    defaultRepo: args.repo,
    ...(deps.cloudflare ? { cloudflare: deps.cloudflare } : {}),
  });

  log.info("agent loop done", {
    issue: args.issue.identifier,
    status: loopResult.status,
    iterations: loopResult.iterations,
    inputTokens: loopResult.inputTokens,
    outputTokens: loopResult.outputTokens,
  });

  const baseRef = BASE_BRANCH;
  const hasCommits = await hasCommitsAhead(worktreePath, baseRef);

  if (loopResult.status !== "finished") {
    if (hasCommits) {
      log.warn("agent did not finish but has commits; opening PR anyway", {
        issue: args.issue.identifier,
        status: loopResult.status,
      });
    } else {
      // No commits and didn't finish cleanly — escalate.
      await escalateToReporter(deps, args, loopResult.status);
      return { status: "agent_failed", branch, summary: null };
    }
  }

  if (!hasCommits) {
    const summary = loopResult.summary ?? "no changes needed";
    await deps.linear.postComment(
      args.issue.id,
      `i looked at this but didn't end up changing anything. ${summary}`,
    );
    await reassignToReporter(deps, args);
    setTerminalState(deps.db, args.issue.id, "escalated");
    return { status: "no_changes", branch, summary };
  }

  // Open the PR.
  const freshUrlForPush = await deps.github.cloneUrl(owner, name);
  await pushBranch({ worktreePath, freshTokenUrl: freshUrlForPush, branch });

  const diff = await getDiff(worktreePath, baseRef);
  const log_ = await getCommitLog(worktreePath, baseRef);

  const prBody = await composePrBody(deps, {
    issue: args.issue,
    branch,
    summary: loopResult.summary,
    diff,
    commitLog: log_,
  });
  const prTitle = await composePrTitle(deps, {
    issue: args.issue,
    summary: loopResult.summary,
    diff,
  });

  const pr = await deps.github.openPullRequest({
    owner,
    repo: name,
    head: branch,
    base: BASE_BRANCH,
    title: prTitle,
    body: prBody,
    draft: false,
  });

  recordPr(deps.db, {
    githubId: pr.number, // we use number as a stable id within a repo for our purposes
    ticketLinearId: args.issue.id,
    repo: args.repo,
    prNumber: pr.number,
    branch,
  });

  try {
    await deps.linear.addPrAttachment(args.issue.id, pr.url, prTitle);
  } catch (err) {
    // Linear auto-detects [TICKET] references in PR bodies and creates
    // its own attachment via the GitHub integration. If we lose that race
    // we get "Duplicate attachment for duplicate url" — non-fatal; the
    // attachment exists either way.
    const message = err instanceof Error ? err.message : String(err);
    if (!/duplicate/i.test(message)) throw err;
    log.debug("attachment already exists (Linear auto-detected)", {
      issue: args.issue.identifier,
      pr: pr.url,
    });
  }
  await deps.linear.postComment(
    args.issue.id,
    `pr is up: ${pr.url}\n\n${loopResult.summary ?? ""}`.trim(),
  );

  return {
    status: "pr_opened",
    prUrl: pr.url,
    prNumber: pr.number,
    branch,
    summary: loopResult.summary,
  };
}

interface RenderTicketOpts {
  worktreePath: string;
  branch: string;
}

function renderTicketForAgent(
  issue: AssignedIssue,
  comments: readonly IssueComment[],
  opts: RenderTicketOpts,
): string {
  const sections: string[] = [];
  sections.push(`Repo is at: ${opts.worktreePath}`);
  sections.push(`Branch: ${opts.branch}`);
  sections.push("");
  sections.push(`Ticket: ${issue.identifier} — ${issue.title}`);
  sections.push("");
  sections.push("Description:");
  sections.push(issue.description ?? "(no description)");
  if (comments.length > 0) {
    sections.push("");
    sections.push(`Comments (${comments.length}, oldest first):`);
    const sorted = [...comments].sort((a, b) =>
      a.createdAt.localeCompare(b.createdAt),
    );
    for (const c of sorted) {
      sections.push(`  ${c.userName ?? "?"} (${c.createdAt}): ${c.body}`);
    }
  }
  sections.push("");
  sections.push("Make the change, commit, and call finish() when done.");
  return sections.join("\n");
}

interface ComposePrBodyArgs {
  issue: AssignedIssue;
  branch: string;
  summary: string | null;
  diff: string;
  commitLog: string;
}

async function composePrBody(
  deps: CodeHandlerDeps,
  args: ComposePrBodyArgs,
): Promise<string> {
  const system = composeSystemPrompt({
    taskInstructions: PR_BODY_TASK_INSTRUCTIONS,
  });
  const truncatedDiff =
    args.diff.length > 12_000
      ? args.diff.slice(0, 12_000) + "\n... (diff truncated)"
      : args.diff;
  const user = [
    `Ticket: ${args.issue.identifier} — ${args.issue.title}`,
    `Branch: ${args.branch}`,
    `Your finish summary: ${args.summary ?? "(none)"}`,
    "",
    "Commits:",
    args.commitLog,
    "",
    "Diff:",
    truncatedDiff,
  ].join("\n");
  return await deps.glm.complete({
    system,
    user,
    temperature: 0.4,
    maxTokens: 1024,
  });
}

interface ComposePrTitleArgs {
  issue: AssignedIssue;
  summary: string | null;
  diff: string;
}

async function composePrTitle(
  deps: CodeHandlerDeps,
  args: ComposePrTitleArgs,
): Promise<string> {
  const system = composeSystemPrompt({
    taskInstructions: PR_TITLE_TASK_INSTRUCTIONS,
  });
  // Heuristic for scope: take the first changed top-level src/ directory
  // from the diff if there is one, else leave it for the model to infer.
  const truncatedDiff =
    args.diff.length > 6000 ? args.diff.slice(0, 6000) + "\n... (truncated)" : args.diff;
  const user = [
    `Ticket: ${args.issue.identifier} — ${args.issue.title}`,
    `Your finish summary: ${args.summary ?? "(none)"}`,
    "",
    "Diff (truncated):",
    truncatedDiff,
  ].join("\n");
  const raw = await deps.glm.complete({
    system,
    user,
    temperature: 0.2,
    maxTokens: 128,
  });
  return raw.trim().split("\n")[0]?.trim() ?? args.issue.title;
}

async function reassignToReporter(
  deps: CodeHandlerDeps,
  args: CodeHandlerArgs,
): Promise<void> {
  if (args.issue.creatorId) {
    try {
      await deps.linear.reassign(args.issue.id, args.issue.creatorId);
    } catch (err) {
      log.warn("could not reassign", {
        issue: args.issue.identifier,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  } else {
    try {
      await deps.linear.unassign(args.issue.id);
    } catch (err) {
      log.warn("could not unassign", {
        issue: args.issue.identifier,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }
}

async function escalateToReporter(
  deps: CodeHandlerDeps,
  args: CodeHandlerArgs,
  reason: string,
): Promise<void> {
  const messages: Record<string, string> = {
    iteration_cap:
      "i hit the iteration cap on this one before getting to a clean stopping point. bouncing it back so a human can take a look.",
    timeout:
      "i ran out of time on this one. bouncing it back — happy to take another swing if someone can point me at the right approach.",
    no_finish:
      "the model returned without calling finish, which usually means it lost the thread. bouncing — i'd want a human to look before i try again.",
    error:
      "ran into an error i couldn't recover from. bouncing back to you.",
  };
  const body =
    messages[reason] ?? `something went wrong (${reason}). bouncing back.`;
  try {
    await deps.linear.postComment(args.issue.id, body);
  } catch (err) {
    log.warn("could not post escalation comment", {
      error: err instanceof Error ? err.message : String(err),
    });
  }
  await reassignToReporter(deps, args);
  setTerminalState(deps.db, args.issue.id, "escalated");
}
